#! /usr/bin/env dshell
@Timeout(Duration(seconds: 600))

import 'dart:io';

import 'package:dshell/dshell.dart';
import 'package:test/test.dart';

/// dshell script generated by:
/// dshell create printerr_test.dart
///
/// See
/// https://pub.dev/packages/dshell#-installing-tab-
///
/// For details on installing dshell.
///

void main() {
  print('Print to stdout using "print');

  stdout.writeln('Print to stdout using "stsdout.writeln"');

  stderr.writeln('Print to stderr using "stderr.writeln"');

  stderr.write('Print to stderr using "stderr.write"');
  stderr.write('\n');
  printerr('Print to stderr using "printerr"');
}
