#! /usr/bin/env dshell
import 'dart:io';


/// dshell script generated by:
/// dshell create printerr_test.dart
///
/// See
/// https://pub.dev/packages/dshell#-installing-tab-
///
/// For details on installing dshell.
///

void main() {
  Platform.environment.forEach((k, v) => print('key:$k, value:$v)}'));
}
