#! /usr/bin/env dshell
import 'dart:io';

import 'package:dshell/dshell.dart';

import 'util/test_paths.dart';

/// dshell script generated by:
/// dshell create printerr_test.dart
///
/// See
/// https://pub.dev/packages/dshell#-installing-tab-
///
/// For details on installing dshell.
///

void main() {
  TestPaths();
  
  print('Print to stdout using "print');

  stdout.writeln('Print to stdout using "stsdout.writeln"');

  stderr.writeln('Print to stderr using "stderr.writeln"');

  stderr.write('Print to stderr using "stderr.write"');
  stderr.write('\n');
  printerr('Print to stderr using "printerr"');
}
