#! /usr/bin/env %dcliName%

// ignore: prefer_relative_imports,  unused_import
import 'package:dcli/dcli.dart';

/// dcli script generated by:
/// dcli create $scriptname
///
/// See
/// https://pub.dev/packages/dcli#-installing-tab-
///
/// For details on installing dcli.
///

void main() {
  print('Hello World');
}
