import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

/// Writes independently compressed resource parts and their parent resource.
class ResourcePacker {
  /// Maximum uncompressed bytes in a generated part class.
  static const int chunkSize = 256 * 1024;

  /// Packs a file without reading or compressing the entire file in memory.
  static void packFile({
    required String source,
    required String destination,
    required String className,
    required String originalPath,
    required String checksum,
    String runtimeImport = 'package:dcli/dcli.dart',
  }) {
    final reader = File(source).openSync();
    final parts = <String>[];
    try {
      while (true) {
        final bytes = reader.readSync(chunkSize);
        if (bytes.isEmpty) {
          break;
        }
        final name = '${className}Part${parts.length}';
        final encoded = base64.encode(gzip.encode(bytes));
        final part = File(
          p.join(p.dirname(destination), '$name.g.dart'),
        ).openSync(mode: FileMode.write);
        try {
          part.writeStringSync('''
// Generated by dcli pack. Do not edit.
import ${dartString(runtimeImport)};

class $name extends PackedResourcePart {
  const $name();
  @override
  int get length => ${bytes.length};
  @override
  String get content =>
''');
          for (var offset = 0; offset < encoded.length; offset += 80) {
            final end = offset + 80 < encoded.length
                ? offset + 80
                : encoded.length;
            part.writeStringSync("      '${encoded.substring(offset, end)}'\n");
          }
          part.writeStringSync('      ;\n}\n');
        } finally {
          part.closeSync();
        }
        parts.add(name);
      }
    } finally {
      reader.closeSync();
    }
    final parent = File(destination).openSync(mode: FileMode.write);
    try {
      parent.writeStringSync(
        '// Generated by dcli pack. Do not edit.\n'
        'import ${dartString(runtimeImport)};\n',
      );
      for (final part in parts) {
        parent.writeStringSync("import '$part.g.dart';\n");
      }
      parent.writeStringSync('''
class $className extends PackedResource {
  const $className();
  @override
  String get checksum => ${dartString(checksum)};
  @override
  String get originalPath => ${dartString(originalPath)};
  @override
  Iterable<PackedResourcePart> get parts => const [
''');
      for (final part in parts) {
        parent.writeStringSync('    $part(),\n');
      }
      parent.writeStringSync('  ];\n}\n');
    } finally {
      parent.closeSync();
    }
  }
}

/// Quotes a string for generated Dart source, including interpolation markers.
String dartString(String value) => jsonEncode(value).replaceAll(r'$', r'\$');
