#! /usr/bin/env dshell

/// dshell script generated by:
/// dshell create echo.dart
///
/// See
/// https://pub.dev/packages/dshell#-installing-tab-
///
/// For details on installing dshell.
///

void main(List<String> args) {
  print('args: ${args.join(', ')}');
}
