#! /usr/bin/env dcli

/// dcli script generated by:
/// dcli create echo.dart
///
/// See
/// https://pub.dev/packages/dcli#-installing-tab-
///
/// For details on installing dcli.
///

void main(List<String> args) {
  print('args: ${args.join(', ')}');
}
