#! /usr/bin/env dshell

import 'package:dshell/dshell.dart';

/// dshell script generated by:
/// dshell create coverage.dart
///
/// See
/// https://pub.dev/packages/dshell#-installing-tab-
///
/// For details on installing dshell.
///

void main() {
  print('Hello World');

  'pub global run coverage:collect_coverage --out=coverage/coverage.json --resume-isolates --wait-paused'
      .start(detached: true);

  'dart --observe test/.test_coverage.dart'.run;

  'pub global run coverage:format_coverage --packages=.dart_tool/package_config.json --in=coverage/coverage.json --lcov --report-on=lib --out=coverage/lcov.info'
      .run;
}
