#! /usr/bin/env dshell
import 'dart:io';
import 'package:dshell/dshell.dart';

/// dshell script generated by:
/// dshell create check_ansi.dart
///
/// See
/// https://pub.dev/packages/dshell#-installing-tab-
///
/// For details on installing dshell.
///

void main() {
  print('ansi supported: ${stdin.supportsAnsiEscapes}');
  print(red('I should be red'));
}
