#! /usr/bin/env dshell
import 'package:dshell/dshell.dart';
import 'package:dshell/src/util/terminal.dart';

/// dshell script generated by:
/// dshell create clear_screen.dart
///
/// See
/// https://pub.dev/packages/dshell#-installing-tab-
///
/// For details on installing dshell.
///

void main() {
  print('Hello World');
  Terminal().clearScreen(mode: TerminalClearMode.all);
  print('Hello World');
}
