#! /usr/bin/env dshell
import 'package:dshell/dshell.dart';

/// dshell script generated by:
/// dshell create run_echo.dart
///
/// See
/// https://pub.dev/packages/dshell#-installing-tab-
///
/// For details on installing dshell.
///

void main() {
  print(pwd);
  'sleep 100'.run;
  'ls *.*'.run;
}
