#! /usr/bin/env dshell
import 'package:dshell/dshell.dart';

/// dshell script generated by:
/// dshell create pipe_to_list.dart
///
/// See
/// https://pub.dev/packages/dshell#-installing-tab-
///
/// For details on installing dshell.
///

void main() {
  var list = ('cat pipe_to_list.dart' | 'grep list').toList();

  print('list ${list.join("\n")}');
}
