#! /usr/bin/env dshell
import 'package:dshell/dshell.dart';

/// dshell script generated by:
/// dshell create run_echo.dart
///
/// See
/// https://pub.dev/packages/dshell#-installing-tab-
///
/// For details on installing dshell.
///

void main(List<String> args) {
  //Settings().setVerbose(true);
  var fqdn = args[0];
  // ask(prompt: "FQDN of test target:");
  var password = args[1];
  //  ask(prompt: 'Password for target:', hidden: true);

  var command =
      "mkdir -p  /tmp/etc/openvpn; echo $password  | sudo -Sp '' cp -R /etc/openvpn/* /tmp/etc/openvpn; echo hi; ls -l /tmp/etc/openvpn; echo $password | sudo -Sp ''  rm -rf /tmp/etc/openvpn ; echo ho; ls /tmp";

  Remote.exec(
      host: fqdn,
      command: command,
      sudo: true,
      password: password,
      progress: Progress.print());

  touch('dshell.txt', create: true);
  Remote.scp(from: 'dshell.txt', toHost: fqdn);

  // // command = 'pwd;ls *';
  // var cmdArgs = <String>[];
  // cmdArgs.clear();
  // cmdArgs.add(
  //     '-T'); // disable the psuedo terminal as we are echoing the password to sudo
  // // cmdArgs.add('-A');
  // cmdArgs.add(fqdn);
  // // cmdArgs.add('--');
  // cmdArgs.add("echo $password | sudo -Skp ''  $command");
  // var progress = Progress((line) => print(green('$line')),
  //     stderr: (line) => print(red(line)));
  // startFromArgs('ssh', cmdArgs, progress: progress, terminal: false);
}
