#! /usr/bin/env dcli

/// dcli script generated by:
/// dcli create hello_world.dart
///
/// See
/// https://pub.dev/packages/dcli#-installing-tab-
///
/// For details on installing dcli.
///

void main() {
  print('Hello World');
}
